spring:
  profiles:
    default: dev
  application:
    name: arkmem
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: ArkMem
    version: 0.1.0-SNAPSHOT
